version: "3.8"

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    # volumes:
    #  - ./volumes/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    # volumes:
    #  - ./volumes/mysql/var/lib/mysql/data:/var/lib/mysql/data
