"""empty message

Revision ID: bd2ebf55aaa7
Revises: 990f4ccc2103
Create Date: 2023-11-19 20:28:23.024960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2ebf55aaa7'
down_revision: Union[str, None] = '990f4ccc2103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('is_up', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'is_up')
    # ### end Alembic commands ###
